package
{
   public dynamic class Main extends SSF2Asset
   {
      
      public function Main()
      {
         super();
         register("id","krystal");
         register("guid","26a0a3ce-7a50-11e6-8b77-86f30ca893d3");
         register("resources",{
            "movieclips":["bullet_hit_effect","grenade_trail","krystal_fspec","krystal_rifleEffect","krystal","krystal_demon_snipe","gatlinggun","krystal_grenade_proj","machinegun","krystal_quake","krystal_sensorbomb","krystal_snipe","krystal_head","Starfox_Symbol"],
            "sounds":["krystal_beep","krystal_dead1","krystal_dead2","krystal_demonsnipe","krystal_hurt1","krystal_hurt10","krystal_hurt11","krystal_hurt12","krystal_hurt3","krystal_hurt7","krystal_jump","krystal_blaster","krystal_downsmash_sfx","krystal_jumpflip","krystal_jumpSound","krystal_jumpSound2","krystal_putaway","krystal_runstart","krystal_runstop","krystal_footstep","krystal_footstep2","krystal_swing_H","krystal_swing_ll","krystal_swing_M","krystal_swing_S","krystal_swing_sl","krystal_swing_sm","krystal_swing_ss","krystal_upsmash_sfx","krystal_dash1","krystal_dash2","landmaster_blast","krystal_voice1","krystal_voice2","krystal_voice3","krystal_voice4","krystal_voice5","krystal_voice6","krystal_voice7","krystal_voice9","krystal_magic","krystal_magic2","fox_victory_v2","krystal_star","krystal_taunt1","krystal_taunt2","krystal_taunt3"]
         });
         register("characters",[this.getKrystal()]);
      }
      
      public function getKrystal() : Object
      {
         var _loc1_:Object = new Object();
         _loc1_ = {
            "classAPI":KrystalExt,
            "statsName":"krystal",
            "displayName":"Krystal",
            "linkage_id":"krystal",
            "power":"krystal",
            "linkage_id2":null,
            "linkage_id_special":null,
            "thumbnail":"krystal_head",
            "seriesIcon":"Starfox_Symbol",
            "width":31,
            "height":50,
            "shield_scale":1.25,
            "revivalEffect":null,
            "weight1":77,
            "max_projectile":12,
            "tetherGrab":false,
            "max_jump":1,
            "holdJump":false,
            "jumpSpeed":22,
            "jumpSpeedMidair":21,
            "jumpStartup":2,
            "shortHopSpeed":14,
            "max_jumpSpeed":7.8,
            "groundToAirMultiplier":0.917,
            "fastFallSpeed":19,
            "gravity":1.85,
            "max_ySpeed":15.5,
            "norm_xSpeed":6,
            "max_xSpeed":12,
            "accel_start":0.333,
            "accel_start_dash":1.12,
            "accel_rate":1.35,
            "accel_rate_air":0.72,
            "decel_rate":-1.3,
            "decel_rate_air":-0.3,
            "dodgeSpeed":17.8,
            "dodgeDecel":-1.45,
            "roll_speed":32,
            "roll_decay":0.7,
            "getup_roll_delay":5,
            "tech_roll_delay":5,
            "climb_roll_delay":11,
            "special_type":1,
            "finalSmashCutin":"krystal_fs_cutin",
            "normalStats_id":"krystal",
            "specialStats_id":"krystal_special",
            "sounds":{
               "jump":"krystal_jump",
               "jump_midair":null,
               "hurt":"krystal_hurt2",
               "hurt2":"krystal_hurt1",
               "hurtBad":"krystal_hurt11",
               "hurtBad2":"krystal_hurt12",
               "dead":"krystal_dead1",
               "dead2":"krystal_dead2",
               "pummel":"krystal_slap",
               "screenko":"krystal_hurt1",
               "starko":"krystal_star",
               "ledge_grab":"krystal_voice2",
               "winTheme":"fox_victory_v2"
            },
            "hurtFrames":3,
            "grabDamage":1,
            "customShield":true,
            "customShieldStartup":5,
            "shield_y_offset":12
         };
         var _loc2_:Object = new Object();
         _loc2_ = {
            "a":{
               "canFallOff":false,
               "attackVoice1_id":"krystal_voice4",
               "attackSound1_id":"krystal_swing_ss",
               "attackSound2_id":"krystal_swing_M",
               "attackBoxes":{"attackBox":{
                  "damage":2,
                  "reversableAngle":false,
                  "sdiDistance":0.01,
                  "priority":2,
                  "hitStun":0,
                  "hitLag":5,
                  "selfHitStun":1,
                  "effect_id":"effect_swordSlash",
                  "direction":90,
                  "power":0,
                  "kbConstant":0,
                  "effectSound":"sw_brawl_hit_S"
               }}
            },
            "a_up":{
               "cancelWhenAirborne":false,
               "refreshRate":4,
               "chargetime_max":40,
               "canFallOff":false,
               "chargeClick":true,
               "attackVoice1_id":"krystal_voice1",
               "attackSound1_id":"krystal_swing_ss",
               "attackBoxes":{
                  "attackBox":{
                     "damage":1,
                     "priority":5,
                     "chargedPriority":6,
                     "hitStun":2,
                     "hitLag":-1.1,
                     "selfHitStun":1,
                     "effect_id":"effect_swordSlash",
                     "direction":100,
                     "power":25,
                     "kbConstant":0,
                     "effectSound":"sw_brawl_hit_S",
                     "reversableAngle":false
                  },
                  "attackBox2":{
                     "damage":1,
                     "priority":5,
                     "chargedPriority":6,
                     "hitStun":2,
                     "hitLag":-1.1,
                     "selfHitStun":1,
                     "effect_id":"effect_swordSlash",
                     "direction":100,
                     "power":25,
                     "kbConstant":0,
                     "effectSound":"sw_brawl_hit_S",
                     "reversableAngle":false
                  }
               }
            },
            "a_up_tilt":{
               "canFallOff":false,
               "attackVoice1_id":"krystal_voice2",
               "attackVoice2_id":"krystal_voice3",
               "attackVoice3_id":"krystal_voice4",
               "attackVoice4_id":"krystal_voice6",
               "attackSound1_id":"krystal_swing_M",
               "attackBoxes":{
                  "attackBox":{
                     "damage":9,
                     "priority":3,
                     "hitStun":2,
                     "selfHitStun":1,
                     "effect_id":"effect_lightHit",
                     "direction":100,
                     "power":56,
                     "kbConstant":64,
                     "effectSound":"brawl_kick_m"
                  },
                  "attackBox2":{
                     "damage":9,
                     "priority":3,
                     "hitStun":2,
                     "selfHitStun":1,
                     "effect_id":"effect_lightHit",
                     "direction":100,
                     "power":56,
                     "kbConstant":64,
                     "effectSound":"brawl_kick_m"
                  }
               }
            },
            "a_forward":{
               "xSpeedDecay":0.97,
               "canFallOff":false,
               "attackVoice1_id":"krystal_voice2",
               "attackVoice2_id":"krystal_voice3",
               "attackVoice3_id":"krystal_voice4",
               "attackVoice4_id":"krystal_voice6",
               "attackSound1_id":"krystal_swing_sm",
               "attackBoxes":{"attackBox":{
                  "damage":8,
                  "priority":3,
                  "hitLag":-1.12,
                  "hitStun":6,
                  "selfHitStun":0,
                  "shieldStunMultiplier":0.5,
                  "effect_id":"effect_hit1",
                  "direction":135,
                  "power":74,
                  "kbConstant":52,
                  "effectSound":"brawl_kick_l",
                  "reversableAngle":false
               }}
            },
            "a_forward_tilt":{
               "canFallOff":false,
               "refreshRate":3,
               "attackVoice1_id":"krystal_voice2",
               "attackVoice2_id":"krystal_voice3",
               "attackVoice3_id":"krystal_voice4",
               "attackVoice4_id":"krystal_voice6",
               "attackSound1_id":"krystal_swing_ss",
               "attackBoxes":{
                  "attackBox":{
                     "damage":2,
                     "priority":3,
                     "hitStun":1,
                     "selfHitStun":0,
                     "effect_id":"effect_swordSlash",
                     "direction":40,
                     "power":20,
                     "kbConstant":8,
                     "reversableAngle":false,
                     "effectSound":"sw_brawl_hit_S"
                  },
                  "attackBox2":{
                     "damage":2,
                     "priority":3,
                     "hitStun":1,
                     "selfHitStun":0,
                     "effect_id":"effect_swordSlash",
                     "direction":225,
                     "power":20,
                     "kbConstant":8,
                     "reversableAngle":false,
                     "effectSound":"sw_brawl_hit_S"
                  }
               }
            },
            "a_forwardsmash":{
               "resetMovement":true,
               "cancelWhenAirborne":false,
               "chargetime_max":40,
               "canFallOff":false,
               "chargeClick":true,
               "attackVoice1_id":"krystal_voice1",
               "attackSound1_id":"krystal_swing_sl",
               "attackBoxes":{
                  "attackBox":{
                     "damage":13,
                     "priority":5,
                     "chargedPriority":6,
                     "hitStun":2,
                     "selfHitStun":2,
                     "camShake":10,
                     "effect_id":"effect_swordSlash",
                     "direction":40,
                     "power":54,
                     "kbConstant":70,
                     "effectSound":"sw_brawl_hit_H"
                  },
                  "attackBox2":{
                     "damage":18,
                     "priority":5,
                     "chargedPriority":6,
                     "hitStun":6,
                     "selfHitStun":4,
                     "camShake":11,
                     "effect_id":"effect_magichit_heavy",
                     "direction":35,
                     "power":50,
                     "kbConstant":82,
                     "effectSound":"brawl_magic_xl"
                  }
               }
            },
            "a_down":{
               "refreshRate":90,
               "resetMovement":true,
               "chargetime_max":40,
               "canFallOff":false,
               "chargeClick":true,
               "attackVoice1_id":"krystal_voice5",
               "attackSound1_id":"krystal_swing_ll",
               "attackBoxes":{
                  "attackBox":{
                     "damage":16,
                     "priority":4,
                     "chargedPriority":5,
                     "hitStun":2,
                     "selfHitStun":2,
                     "camShake":10,
                     "effect_id":"effect_heavyHit",
                     "direction":40,
                     "power":50,
                     "kbConstant":92,
                     "effectSound":"brawl_kick_l"
                  },
                  "attackBox2":{
                     "damage":16,
                     "priority":4,
                     "chargedPriority":5,
                     "hitStun":2,
                     "selfHitStun":2,
                     "camShake":10,
                     "effect_id":"effect_heavyHit",
                     "direction":40,
                     "power":50,
                     "kbConstant":92,
                     "effectSound":"brawl_kick_l"
                  }
               }
            },
            "crouch_attack":{
               "canFallOff":false,
               "attackVoice1_id":"krystal_voice2",
               "attackVoice2_id":"krystal_voice3",
               "attackVoice3_id":"krystal_voice4",
               "attackVoice4_id":"krystal_voice6",
               "attackSound1_id":"krystal_swing_S",
               "attackBoxes":{"attackBox":{
                  "damage":7,
                  "priority":3,
                  "hitStun":2,
                  "hitLag":-1,
                  "selfHitStun":0,
                  "effect_id":"effect_hit1",
                  "direction":85,
                  "power":42,
                  "kbConstant":90,
                  "effectSound":"brawl_kick_m"
               }}
            },
            "a_air":{
               "allowControl":true,
               "canFallOff":true,
               "cancelWhenAirborne":true,
               "cpuAttackQueue":"b_down;a_up;a_forward;a_forwardsmash",
               "attackVoice1_id":"krystal_voice2",
               "attackVoice2_id":"krystal_voice3",
               "attackVoice3_id":"krystal_voice4",
               "attackVoice4_id":"krystal_voice6",
               "attackSound1_id":"krystal_swing_H",
               "attackBoxes":{
                  "attackBox":{
                     "damage":13,
                     "priority":3,
                     "hitStun":2,
                     "hitLag":-1.12,
                     "selfHitStun":1,
                     "effect_id":"effect_heavyHit",
                     "direction":65,
                     "power":45,
                     "kbConstant":90,
                     "effectSound":"brawl_kick_l"
                  },
                  "attackBox2":{
                     "damage":13,
                     "priority":3,
                     "hitStun":2,
                     "hitLag":-1.12,
                     "selfHitStun":1,
                     "effect_id":"effect_heavyHit",
                     "direction":65,
                     "power":45,
                     "kbConstant":90,
                     "effectSound":"brawl_kick_l"
                  }
               }
            },
            "a_air_up":{
               "allowControl":true,
               "canFallOff":true,
               "cancelWhenAirborne":true,
               "attackVoice1_id":"krystal_voice3",
               "attackVoice2_id":"krystal_voice4",
               "attackSound1_id":"krystal_swing_sm",
               "attackBoxes":{
                  "attackBox":{
                     "damage":13,
                     "priority":5,
                     "hitStun":4,
                     "selfHitStun":3,
                     "effect_id":"effect_swordSlash",
                     "direction":90,
                     "power":30,
                     "kbConstant":85,
                     "effectSound":"sw_brawl_hit_S"
                  },
                  "attackBox2":{
                     "damage":16,
                     "priority":5,
                     "hitStun":6,
                     "selfHitStun":9,
                     "effect_id":"effect_magichit_heavy",
                     "direction":90,
                     "power":40,
                     "kbConstant":88,
                     "effectSound":"brawl_magic_xl"
                  }
               }
            },
            "a_air_forward":{
               "allowControl":true,
               "canFallOff":true,
               "cancelWhenAirborne":true,
               "cpuAttackQueue":"b_down;a_air;a_air_forward;a_air_down;b_down_air;a_up;a_forward;a_forwardsmash",
               "attackVoice1_id":"krystal_voice2",
               "attackVoice2_id":"krystal_voice3",
               "attackVoice3_id":"krystal_voice4",
               "attackVoice4_id":"krystal_voice6",
               "attackSound1_id":"krystal_swing_S",
               "attackSound2_id":"krystal_swing_M",
               "attackSound3_id":"krystal_swing_ll",
               "attackBoxes":{"attackBox":{
                  "damage":5,
                  "priority":2,
                  "hitStun":6,
                  "hitLag":-1.1,
                  "selfHitStun":3,
                  "effect_id":"effect_hit1",
                  "direction":35,
                  "reversableAngle":false,
                  "power":30,
                  "kbConstant":30,
                  "effectSound":"brawl_kick_l"
               }}
            },
            "a_air_backward":{
               "allowControl":true,
               "canFallOff":true,
               "cancelWhenAirborne":true,
               "attackVoice1_id":"krystal_voice2",
               "attackVoice2_id":"krystal_voice3",
               "attackVoice3_id":"krystal_voice4",
               "attackVoice4_id":"krystal_voice6",
               "attackSound1_id":"krystal_swing_M",
               "attackBoxes":{
                  "attackBox":{
                     "damage":11,
                     "priority":3,
                     "hitStun":4,
                     "hitLag":-1.1,
                     "selfHitStun":1,
                     "effect_id":"effect_hit1",
                     "direction":135,
                     "reversableAngle":false,
                     "power":40,
                     "kbConstant":88,
                     "effectSound":"brawl_kick_l"
                  },
                  "attackBox2":{
                     "damage":11,
                     "priority":3,
                     "hitStun":4,
                     "hitLag":-1.1,
                     "selfHitStun":1,
                     "effect_id":"effect_hit1",
                     "direction":45,
                     "power":40,
                     "kbConstant":88,
                     "effectSound":"brawl_kick_l"
                  },
                  "attackBox3":{
                     "damage":11,
                     "priority":3,
                     "hitStun":4,
                     "hitLag":-1.1,
                     "selfHitStun":1,
                     "effect_id":"effect_hit1",
                     "direction":45,
                     "reversableAngle":false,
                     "power":40,
                     "kbConstant":88,
                     "effectSound":"brawl_kick_l"
                  }
               }
            },
            "a_air_down":{
               "allowControl":true,
               "canFallOff":true,
               "cancelWhenAirborne":true,
               "cpuAttackQueue":"b_down;a_air;a_air_forward;a_air_down;b_down_air;a_up;a_forward;a_forwardsmash",
               "attackVoice1_id":"krystal_voice9",
               "attackVoice2_id":"krystal_voice2",
               "attackSound1_id":"krystal_swing_sm",
               "attackBoxes":{
                  "attackBox":{
                     "damage":14,
                     "priority":3,
                     "hitStun":4,
                     "hitLag":-1,
                     "selfHitStun":4,
                     "direction":75,
                     "power":38,
                     "kbConstant":85,
                     "effectSound":"sw_brawl_hit_H",
                     "effect_id":"effect_swordSlash"
                  },
                  "attackBox2":{
                     "damage":18,
                     "priority":3,
                     "hitStun":6,
                     "hitLag":-1,
                     "selfHitStun":9,
                     "effect_id":"effect_magichit_heavy",
                     "direction":270,
                     "power":62,
                     "kbConstant":95,
                     "effectSound":"brawl_magic_xl"
                  }
               }
            },
            "b":{
               "refreshRate":100,
               "combo_max":99999,
               "canFallOff":false,
               "isLongRangeMove":true,
               "canBeAbsorbed":true,
               "disableForCPU":false,
               "chargeInAir":false,
               "linkFrames":true,
               "attackSound1_id":"krystal_snipershot",
               "attackSound2_id":"krystal_putaway",
               "attackSound3_id":"krystal_readysniper",
               "attackBoxes":{"attackBox":{
                  "damage":20,
                  "priority":4,
                  "hitStun":3,
                  "hitLag":0.9,
                  "selfHitStun":0,
                  "direction":10,
                  "power":0,
                  "kbConstant":16,
                  "effectSound":"sw_strongslash"
               }}
            },
            "b_air":{
               "refreshRate":100,
               "allowControl":true,
               "allowControlGround":false,
               "combo_max":99999,
               "isLongRangeMove":true,
               "chargeInAir":false,
               "linkFrames":true,
               "attackSound1_id":"krystal_snipershot",
               "attackSound2_id":"krystal_putaway",
               "attackSound3_id":"krystal_readysniper",
               "attackBoxes":{"attackBox":{
                  "damage":20,
                  "priority":4,
                  "hitStun":3,
                  "hitLag":0.9,
                  "selfHitStun":0,
                  "direction":10,
                  "power":0,
                  "kbConstant":16,
                  "effectSound":"sw_strongslash"
               }}
            },
            "b_up":{
               "allowFastFall":false,
               "cancelWhenAirborne":false,
               "xSpeedDecayAir":-0.35,
               "allowControl":true,
               "controlDirection":true,
               "attackSound1_id":"krystal_magic",
               "attackSound2_id":"krystal_magic2",
               "attackBoxes":{
                  "attackBox":{
                     "damage":4,
                     "priority":3,
                     "hitStun":6,
                     "selfHitStun":3,
                     "hitLag":-1.2,
                     "effect_id":"effect_magichit_heavy",
                     "direction":270,
                     "reversableAngle":false,
                     "power":45,
                     "kbConstant":65,
                     "shock":true,
                     "effectSound":"brawl_magic_xl"
                  },
                  "attackBox2":{
                     "damage":4,
                     "priority":3,
                     "hitStun":6,
                     "selfHitStun":3,
                     "hitLag":-1.2,
                     "effect_id":"effect_magichit_heavy",
                     "direction":270,
                     "reversableAngle":false,
                     "power":45,
                     "kbConstant":65,
                     "shock":true,
                     "effectSound":"brawl_magic_xl"
                  }
               }
            },
            "b_up_air":{
               "cancelWhenAirborne":false,
               "allowFastFall":false,
               "xSpeedDecayAir":-0.35,
               "allowControl":true,
               "isHorizontalRecoveryMove":true,
               "isRecoveryMove":true,
               "linkFrames":true,
               "controlDirection":true,
               "attackSound1_id":"krystal_magic",
               "attackSound2_id":"krystal_magic2",
               "attackBoxes":{
                  "attackBox":{
                     "damage":4,
                     "priority":3,
                     "hitStun":6,
                     "selfHitStun":2,
                     "hitLag":-1.2,
                     "effect_id":"effect_magichit_heavy",
                     "direction":270,
                     "reversableAngle":false,
                     "power":45,
                     "kbConstant":65,
                     "shock":true,
                     "effectSound":"brawl_magic_xl"
                  },
                  "attackBox2":{
                     "damage":4,
                     "priority":3,
                     "hitStun":6,
                     "selfHitStun":2,
                     "hitLag":-1.2,
                     "effect_id":"effect_magichit_heavy",
                     "direction":270,
                     "reversableAngle":false,
                     "power":45,
                     "kbConstant":65,
                     "shock":true,
                     "effectSound":"brawl_magic_xl"
                  }
               }
            },
            "b_forward":{
               "resetMovement":true,
               "canFallOff":false,
               "cancel":true,
               "cancelWhenAirborne":false,
               "xSpeedDecay":-2,
               "xSpeedDecayAir":-0.5,
               "air_ease":0,
               "attackSound1_id":"krystal_dash1",
               "attackSound2_id":"krystal_dash2",
               "attackBoxes":{"attackBox":{
                  "hasEffect":true,
                  "damage":8,
                  "direction":80,
                  "hitLag":-1.15,
                  "power":75,
                  "kbConstant":55,
                  "reversableAngle":false,
                  "selfHitStun":8,
                  "hitStun":2,
                  "effect_id":"effect_hit1"
               }}
            },
            "b_forward_air":{
               "resetMovement":true,
               "canFallOff":true,
               "cancelWhenAirborne":false,
               "cancel":true,
               "xSpeedDecay":-2,
               "xSpeedDecayAir":-0.5,
               "air_ease":0,
               "isHorizontalRecoveryMove":true,
               "attackSound1_id":"krystal_dash1",
               "attackSound2_id":"krystal_dash2",
               "attackBoxes":{"attackBox":{
                  "hasEffect":true,
                  "damage":8,
                  "direction":80,
                  "hitLag":-1.15,
                  "power":75,
                  "kbConstant":55,
                  "reversableAngle":false,
                  "selfHitStun":8,
                  "hitStun":2,
                  "effect_id":"effect_hit1"
               }}
            },
            "b_down":{"attackBoxes":{
               "attackBox":{
                  "damage":8,
                  "priority":-1,
                  "hitStun":2,
                  "hitLag":-1.1,
                  "selfHitStun":1,
                  "effect_id":"effect_lightHit",
                  "direction":90,
                  "reverse_character":false,
                  "power":90,
                  "kbConstant":50,
                  "shock":true,
                  "effectSound":"brawl_fire_l"
               },
               "attackBox2":{
                  "hasEffect":false,
                  "selfHitStun":0,
                  "hitStun":0,
                  "reverse_projectile":true
               }
            }},
            "b_down_air":{
               "allowControl":true,
               "allowControlGround":false,
               "maintainSpeed":true,
               "attackBoxes":{
                  "attackBox":{
                     "damage":8,
                     "priority":-1,
                     "hitStun":2,
                     "hitLag":-1.1,
                     "selfHitStun":1,
                     "effect_id":"effect_lightHit",
                     "direction":90,
                     "reverse_character":false,
                     "power":90,
                     "kbConstant":50,
                     "shock":true,
                     "effectSound":"brawl_fire_l"
                  },
                  "attackBox2":{
                     "hasEffect":false,
                     "selfHitStun":0,
                     "hitStun":0,
                     "reverse_projectile":true
                  }
               }
            },
            "throw_up":{
               "canFallOff":false,
               "attackSound1_id":"krystal_blaster",
               "attackSound2_id":"krystal_putaway",
               "attackBoxes":{"attackBox":{
                  "damage":8,
                  "priority":0,
                  "hitStun":2,
                  "selfHitStun":1,
                  "direction":85,
                  "power":95,
                  "kbConstant":45,
                  "effectSound":null,
                  "bypassNonGrabbed":true
               }}
            },
            "throw_forward":{
               "canFallOff":false,
               "attackSound1_id":"krystal_swing_ss",
               "attackBoxes":{
                  "attackBox":{
                     "damage":3,
                     "bypassGrabbed":true,
                     "effect_id":"effect_swordSlash",
                     "direction":45,
                     "power":60,
                     "kbConstant":100,
                     "effectSound":"sw_brawl_hit_M"
                  },
                  "attackBox2":{
                     "damage":8,
                     "bypassNonGrabbed":true,
                     "hitStun":6,
                     "hitLag":-1.04,
                     "selfHitStun":1,
                     "effect_id":"effect_swordSlash",
                     "direction":55,
                     "power":82,
                     "kbConstant":50,
                     "effectSound":"sw_brawl_hit_M"
                  }
               }
            },
            "throw_back":{
               "flip":true,
               "canFallOff":false,
               "attackBoxes":{
                  "attackBox":{
                     "damage":3,
                     "bypassGrabbed":true,
                     "direction":45,
                     "power":60,
                     "kbConstant":100,
                     "effectSound":"brawl_kick_l",
                     "effect_id":"effect_heavyHit"
                  },
                  "attackBox2":{
                     "damage":11,
                     "bypassNonGrabbed":true,
                     "priority":0,
                     "hitStun":2,
                     "selfHitStun":2,
                     "direction":42,
                     "power":44,
                     "kbConstant":85,
                     "effectSound":"brawl_kick_l",
                     "effect_id":"effect_heavyHit"
                  }
               }
            },
            "throw_down":{
               "refreshRate":30,
               "canFallOff":false,
               "attackBoxes":{"attackBox":{
                  "forceTumbleFall":true,
                  "bypassGrabbed":true,
                  "damage":6,
                  "priority":0,
                  "hitStun":4,
                  "hitLag":17,
                  "selfHitStun":2,
                  "effect_id":"effect_icehit",
                  "effectSound":"iceflower_shoot",
                  "direction":270,
                  "power":20,
                  "kbConstant":0,
                  "meteorBounce":false,
                  "effectSound":null,
                  "freeze":18
               }}
            },
            "ledge_attack":{
               "canFallOff":false,
               "maintainSpeed":true,
               "attackVoice1_id":"krystal_voice2",
               "attackVoice2_id":"krystal_voice3",
               "attackVoice3_id":"krystal_voice4",
               "attackVoice4_id":"krystal_voice6",
               "attackSound1_id":"krystal_swing_S",
               "attackBoxes":{"attackBox":{
                  "damage":7,
                  "priority":3,
                  "hitStun":2,
                  "selfHitStun":1,
                  "direction":45,
                  "power":75,
                  "kbConstant":25,
                  "effect_id":"effect_hit2",
                  "effectSound":"brawl_kick_m"
               }}
            },
            "getup_attack":{
               "attackVoice1_id":"krystal_voice2",
               "attackVoice2_id":"krystal_voice3",
               "attackVoice3_id":"krystal_voice4",
               "attackVoice4_id":"krystal_voice6",
               "attackSound1_id":"krystal_swing_M",
               "attackBoxes":{"attackBox":{
                  "damage":5,
                  "priority":3,
                  "hitStun":2,
                  "selfHitStun":2,
                  "effect_id":"effect_heavyHit",
                  "direction":-4,
                  "power":80,
                  "kbConstant":25,
                  "effectSound":"brawl_kick_l"
               }}
            },
            "kirby":{
               "refreshRate":100,
               "combo_max":99999,
               "canBeAbsorbed":true,
               "disableForCPU":true,
               "chargeInAir":false,
               "linkFrames":true,
               "attackSound1_id":"krystal_blaster",
               "attackSound2_id":"krystal_putaway",
               "attackBoxes":{"attackBox":{
                  "damage":20,
                  "priority":4,
                  "hitStun":3,
                  "hitLag":0.9,
                  "selfHitStun":0,
                  "direction":10,
                  "power":-1000,
                  "kbConstant":16,
                  "effectSound":"sw_strongslash"
               }}
            },
            "kirby_air":{
               "refreshRate":100,
               "allowControl":true,
               "allowControlGround":false,
               "combo_max":99999,
               "disableForCPU":true,
               "chargeInAir":false,
               "linkFrames":true,
               "attackSound1_id":"krystal_blaster",
               "attackSound2_id":"krystal_putaway",
               "attackBoxes":{"attackBox":{
                  "damage":20,
                  "priority":4,
                  "hitStun":3,
                  "hitLag":0.9,
                  "selfHitStun":0,
                  "direction":10,
                  "power":-1000,
                  "kbConstant":16,
                  "effectSound":"sw_strongslash"
               }}
            },
            "special":{
               "resetMovement":true,
               "cancelWhenAirborne":false,
               "air_ease":0,
               "canUseInAir":true,
               "allowFastFall":false,
               "attackSound1_id":"krystal_blaster",
               "attackSound2_id":"krystal_putaway",
               "attackBoxes":{"attackBox":{
                  "damage":18,
                  "hitStun":0,
                  "selfHitStun":0,
                  "effect_id":"effect_heavyHit",
                  "pitfall":120,
                  "direction":270,
                  "power":65,
                  "kbConstant":75,
                  "bypassShield":true,
                  "effectSound":"brawl_kick_l"
               }}
            },
            "item_jab":{
               "allowControl":false,
               "maintainSpeed":false,
               "cancelWhenAirborne":true,
               "canFallOff":false,
               "canUseInAir":false
            },
            "item_tilt":{
               "allowControl":false,
               "maintainSpeed":false,
               "cancelWhenAirborne":true,
               "canFallOff":false,
               "canUseInAir":false
            },
            "item_dash":{
               "allowControl":false,
               "maintainSpeed":false,
               "cancelWhenAirborne":true,
               "canFallOff":false,
               "canUseInAir":false
            },
            "item_smash":{
               "chargetime_max":40,
               "chargeClick":true,
               "allowControl":false,
               "maintainSpeed":false,
               "cancelWhenAirborne":true,
               "canFallOff":false,
               "canUseInAir":false,
               "attackVoice1_id":"krystal_voice5"
            },
            "item_homerun":{
               "allowControl":false,
               "maintainSpeed":false,
               "cancelWhenAirborne":true,
               "canFallOff":false,
               "canUseInAir":false,
               "attackVoice1_id":"krystal_voice1"
            },
            "item_fan":{
               "allowControl":false,
               "maintainSpeed":false,
               "cancelWhenAirborne":true,
               "canFallOff":false,
               "canUseInAir":false
            },
            "item_shoot":{
               "allowControl":false,
               "maintainSpeed":false,
               "canFallOff":false
            },
            "item_heavyshoot":{
               "allowControl":false,
               "maintainSpeed":false,
               "canFallOff":false
            },
            "item_raise":{
               "maintainSpeed":false,
               "canFallOff":false
            },
            "item_screw":{
               "refreshRate":1,
               "allowControl":true,
               "air_ease":0,
               "maintainSpeed":true,
               "cancelWhenAirborne":false,
               "canFallOff":false,
               "canUseInAir":true,
               "attackBoxes":{
                  "attackBox":{
                     "damage":1,
                     "priority":5,
                     "hitStun":1,
                     "selfHitStun":0,
                     "effect_id":"effect_lightHit",
                     "direction":95,
                     "power":125,
                     "kbConstant":10,
                     "stackKnockback":false,
                     "shock":true,
                     "effectSound":"brawl_kick_s"
                  },
                  "attackBox2":{
                     "damage":1,
                     "priority":5,
                     "hitStun":1,
                     "selfHitStun":0,
                     "effect_id":"effect_lightHit",
                     "direction":95,
                     "power":125,
                     "kbConstant":10,
                     "stackKnockback":false,
                     "shock":true,
                     "effectSound":"brawl_kick_s"
                  }
               }
            },
            "item_firedash":{
               "allowControl":false,
               "air_ease":0,
               "maintainSpeed":true,
               "cancelWhenAirborne":false,
               "canFallOff":false,
               "canUseInAir":true,
               "attackBoxes":{"attackBox":{
                  "damage":8,
                  "effect_id":"effect_firehit_heavy",
                  "direction":45,
                  "power":25,
                  "kbConstant":110,
                  "burn":true,
                  "effectSound":"brawl_fire_l"
               }}
            },
            "item_bubblebounce":{
               "allowControl":true,
               "air_ease":-1,
               "maintainSpeed":true,
               "cancelWhenAirborne":false,
               "canFallOff":false,
               "canUseInAir":true,
               "xSpeedCap":6,
               "xSpeedAccel":0.75,
               "xSpeedAccelAir":0.75,
               "xSpeedDecay":0.99,
               "xSpeedDecayAir":0.99,
               "attackBoxes":{"attackBox":{
                  "damage":6,
                  "effect_id":"effect_waterhit_heavy",
                  "direction":270,
                  "power":20,
                  "kbConstant":80,
                  "effectSound":"sfx_waterhit_m"
               }}
            }
         };
         var _loc3_:Object = {
            "krystal_snipe":{
               "classAPI":SSF2Projectile,
               "linkage_id":"krystal_snipe",
               "time_max":36,
               "xspeed":45,
               "rideGround":false,
               "xoffset":46,
               "yoffset":-20,
               "attack_idle":{"attackBoxes":{"attackBox":{
                  "damage":10,
                  "priority":-1,
                  "hitStun":6,
                  "selfHitStun":2,
                  "effect_id":"effect_hit1",
                  "direction":40,
                  "reversableAngle":false,
                  "power":42,
                  "sdiDistance":1,
                  "kbConstant":77,
                  "effectSound":"sw_bigscratch"
               }}}
            },
            "krystal_grenade_proj":{
               "classAPI":SSF2Projectile,
               "linkage_id":"krystal_grenade_proj",
               "time_max":999,
               "gravity":1,
               "maxgravity":10,
               "canBeAbsorbed":false,
               "xoffset":0,
               "yoffset":-21,
               "attack_idle":{"attackBoxes":{
                  "attackBox":{
                     "damage":1e-8,
                     "ignoreChargeDamage":true,
                     "hitStun":0,
                     "selfHitStun":0,
                     "effect_id":null,
                     "direction":0,
                     "power":0,
                     "kbConstant":0,
                     "effectSound":"brawl_punch_s",
                     "hasEffect":false
                  },
                  "attackBox2":{
                     "damage":1e-8,
                     "ignoreChargeDamage":true,
                     "hitStun":0,
                     "selfHitStun":0,
                     "effect_id":null,
                     "direction":0,
                     "power":0,
                     "kbConstant":0,
                     "effectSound":"brawl_punch_s",
                     "hasEffect":false
                  }
               }}
            },
            "krystal_quake":{
               "classAPI":SSF2Projectile,
               "linkage_id":"krystal_quake",
               "time_max":999,
               "gravity":0,
               "maxgravity":0,
               "canBePocketed":false,
               "canBeReversed":false,
               "canBeAbsorbed":false,
               "xoffset":0,
               "yoffset":0,
               "attack_idle":{"attackBoxes":{
                  "attackBox":{
                     "damage":3,
                     "priority":-1,
                     "hitStun":2,
                     "selfHitStun":0,
                     "effect_id":"effect_hit2",
                     "direction":90,
                     "power":10,
                     "kbConstant":10,
                     "effectSound":"brawl_kick_l",
                     "forceTumbleFall":true,
                     "onlyAffectsGround":true
                  },
                  "attackBox2":{
                     "damage":3,
                     "priority":-1,
                     "hitStun":2,
                     "selfHitStun":0,
                     "effect_id":"effect_hit2",
                     "direction":90,
                     "power":10,
                     "kbConstant":10,
                     "effectSound":"brawl_kick_l",
                     "forceTumbleFall":true,
                     "onlyAffectsGround":true
                  }
               }}
            },
            "krystal_fireburst":{
               "classAPI":SSF2Projectile,
               "linkage_id":"krystal_fireburst",
               "time_max":30,
               "gravity":0,
               "maxgravity":0,
               "canBePocketed":false,
               "canBeReversed":false,
               "canBeAbsorbed":false,
               "xoffset":0,
               "yoffset":0,
               "attack_idle":{"attackBoxes":{"attackBox":{
                  "damage":20,
                  "priority":-1,
                  "hitStun":4,
                  "selfHitStun":0,
                  "effect_id":"effect_firehit_heavy",
                  "direction":50,
                  "power":60,
                  "kbConstant":85,
                  "bypassShield":true,
                  "bypassHeavyArmor":true,
                  "bypassSuperArmor":true,
                  "effectSound":"brawl_bomb_l"
               }}}
            }
         };
         var _loc4_:Object = null;
         return {
            "cData":_loc1_,
            "aData":_loc2_,
            "pData":_loc3_,
            "iData":_loc4_
         };
      }
   }
}

